config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :homejoyms
  devise_scope :user do
  authenticated do
  
  root to:'homejoyms#index', as: :authenticated_root
  end
  root to:"devise/sessions#new"
  end

end

app/models/homejoym.rb
class Homejoym < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homejoyms_controller.rb
class HomejoymsController < ApplicationController
  before_action :set_homejoym, only: [:show, :edit, :update, :destroy]

  # GET /homejoyms
  # GET /homejoyms.json
  def index
    @homejoyms = Homejoym.all
  end

  # GET /homejoyms/1
  # GET /homejoyms/1.json
  def show
  end

  # GET /homejoyms/new
  def new
    @homejoym = Homejoym.new
  end

  # GET /homejoyms/1/edit
  def edit
  end

  # POST /homejoyms
  # POST /homejoyms.json
  def create
    @homejoym = Homejoym.new(homejoym_params)

    respond_to do |format|
      if @homejoym.save
        format.html { redirect_to @homejoym, notice: 'Homejoym was successfully created.' }
        format.json { render :show, status: :created, location: @homejoym }
      else
        format.html { render :new }
        format.json { render json: @homejoym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homejoyms/1
  # PATCH/PUT /homejoyms/1.json
  def update
    respond_to do |format|
      if @homejoym.update(homejoym_params)
        format.html { redirect_to @homejoym, notice: 'Homejoym was successfully updated.' }
        format.json { render :show, status: :ok, location: @homejoym }
      else
        format.html { render :edit }
        format.json { render json: @homejoym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homejoyms/1
  # DELETE /homejoyms/1.json
  def destroy
    @homejoym.destroy
    respond_to do |format|
      format.html { redirect_to homejoyms_url, notice: 'Homejoym was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homejoym
      @homejoym = Homejoym.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homejoym_params
      params.require(:homejoym).permit(:selectservice, :payment, :address, :numofworkers, :packages, :ratecard)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homejoyms_helper.rb
module HomejoymsHelper
end

app/views/homejoyms/_form.html.erb
<%= form_for @homejoym, :html => { :class => "form-horizontal homejoym" } do |f| %>

  <% if @homejoym.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@homejoym.errors.count, "error") %> prohibited this homejoym from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @homejoym.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :selectservice, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :selectservice, :class => 'form-control' %>
    </div>
    <%=f.error_span(:selectservice) %>
  </div>
  <div class="form-group">
    <%= f.label :payment, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :payment, :class => 'form-control' %>
    </div>
    <%=f.error_span(:payment) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :numofworkers, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :numofworkers, :class => 'form-control' %>
    </div>
    <%=f.error_span(:numofworkers) %>
  </div>
  <div class="form-group">
    <%= f.label :packages, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :packages, :class => 'form-control' %>
    </div>
    <%=f.error_span(:packages) %>
  </div>
  <div class="form-group">
    <%= f.label :ratecard, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ratecard, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ratecard) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                homejoyms_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/homejoyms/edit.html.erb
<%- model_class = Homejoym -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/homejoyms/index.html.erb
<%- model_class = Homejoym -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:selectservice) %></th>
      <th><%= model_class.human_attribute_name(:payment) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:numofworkers) %></th>
      <th><%= model_class.human_attribute_name(:packages) %></th>
      <th><%= model_class.human_attribute_name(:ratecard) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @homejoyms.each do |homejoym| %>
      <tr>
        <td><%= link_to homejoym.id, homejoym_path(homejoym) %></td>
        <td><%= homejoym.selectservice %></td>
        <td><%= homejoym.payment %></td>
        <td><%= homejoym.address %></td>
        <td><%= homejoym.numofworkers %></td>
        <td><%= homejoym.packages %></td>
        <td><%= homejoym.ratecard %></td>
        <td><%=l homejoym.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_homejoym_path(homejoym), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      homejoym_path(homejoym),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_homejoym_path,
            :class => 'btn btn-primary' %>

app/views/homejoyms/new.html.erb
<%- model_class = Homejoym -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/homejoyms/show.html.erb
<%- model_class = Homejoym -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:selectservice) %>:</strong></dt>
  <dd><%= @homejoym.selectservice %></dd>
  <dt><strong><%= model_class.human_attribute_name(:payment) %>:</strong></dt>
  <dd><%= @homejoym.payment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @homejoym.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:numofworkers) %>:</strong></dt>
  <dd><%= @homejoym.numofworkers %></dd>
  <dt><strong><%= model_class.human_attribute_name(:packages) %>:</strong></dt>
  <dd><%= @homejoym.packages %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ratecard) %>:</strong></dt>
  <dd><%= @homejoym.ratecard %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              homejoyms_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_homejoym_path(@homejoym), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              homejoym_path(@homejoym),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomejoymgmtApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>